"""
PEGASUS WORLD CUP INVITATIONAL G1 - ANALYSIS
Gulfstream Park, January 24, 2026 - Race 13
Comparing OLD vs NEW system predictions
"""

print("="*80)
print("PEGASUS WORLD CUP INVITATIONAL GRADE 1 - RACE ANALYSIS")
print("="*80)
print("Track: Gulfstream Park")
print("Date: January 24, 2026")
print("Distance: 1.25 Mile (9 Furlongs)")
print("Purse: $3,000,000")
print("Grade: I (Elite Stakes)")
print("Field Size: 14 horses")
print()

print("="*80)
print("NEW SYSTEM: RACE CLASS CLASSIFICATION")
print("="*80)
print("Race Type: PWCInvit-G1 (Pegasus World Cup Invitational)")
print("Class Type: Grade 1 Stakes")
print(">>> HIERARCHY LEVEL: 10 (BASE 7 + G1 BOOST +3)")
print(">>> CLASS WEIGHT: 10.00 (MAXIMUM)")
print()
print("WHAT THIS MEANS:")
print("  * This is the HIGHEST class weight in our system")
print("  * Heavily rewards horses with proven G1 form")
print("  * Class ratings and Prime Power are critical")
print("  * Recent form and speed figures matter greatly")
print("  * Layoffs are more penalized at elite level")
print()

print("="*80)
print("OLD SYSTEM PREDICTIONS")
print("="*80)
print()
print("MOST LIKELY FINISHING ORDER (Old System):")
print("  1st: #4 Banishing (16/1) - 65.0% conditional probability")
print("  2nd: #9 Captain Cook (16/1) - 94.2% conditional probability")
print("  3rd: #5 Skippylongstocking (21/1) - 27.4% conditional probability")
print("  4th: #2 British Isles (50/1) - 30.9% conditional probability")
print("  5th: #12 Brotha Keny (50/1) - 34.8% conditional probability")
print()
print("A-GROUP (Key Win Contenders):")
print("  * #4 Banishing (ML 20/1 --> Live 16/1)")
print()
print("B-GROUP (Primary Challengers):")
print("  * #2 British Isles (ML 20/1 --> Live 50/1)")
print("  * #5 Skippylongstocking (ML 15/1 --> Live 21/1)")
print("  * #9 Captain Cook (ML 15/1 --> Live 16/1)")
print()
print("C-GROUP (Underneath Keys):")
print("  * #7 Tappan Street (ML 6/1 --> Live 10/1)")
print("  * #8 Poster (ML 20/1)")
print("  * #11 White Abarrio (ML 4/1 --> Live 9/2)")
print("  * #12 Brotha Keny (ML 30/1 --> Live 50/1)")
print()

print("="*80)
print("KEY HORSE RANKINGS - NEW SYSTEM")
print("="*80)
print()
print("PRIME POWER (Overall Ability Rating):")
print("  1. #11 White Abarrio: 147.8")
print("  2. #3 Full Serrano: 145.2")
print("  3. #1 Disco Time: 144.3")
print("  4. #6 Madaket Road: 143.4")
print("  5. #9 Captain Cook: 143.1")
print()
print("CLASS RATING (Historical Class Level):")
print("  1. #11 White Abarrio: 120.9 (Highest)")
print("  2. #1 Disco Time: 120.4")
print("  3. #3 Full Serrano: 120.0")
print("  4. #7 Tappan Street: 120.0")
print("  5. #4 Banishing: 119.3")
print()
print("LAST RACE SPEED FIGURE:")
print("  1. #2 British Isles: 105")
print("  2. #10 Mika: 102")
print("  3. #11 White Abarrio: 100")
print("  4. #4 Banishing: 97")
print("  5. #6 Madaket Road: 97")
print()

print("="*80)
print("TOP CONTENDERS - DETAILED ANALYSIS")
print("="*80)
print()
print("#11 WHITE ABARRIO (4/1 Favorite)")
print("  Record: 24: 10-2-3, $7,151,920")
print("  STRENGTHS:")
print("    * Highest Prime Power (147.8)")
print("    * Highest Class Rating (120.9)")
print("    * Won this race last year (defending champion)")
print("    * Won BC Classic-G1 in 2023")
print("    * 8-1-0 record at Gulfstream Park")
print("  CONCERNS:")
print("    * 146 days since last race (longest layoff in field)")
print("    * Last race: 5th in JC Gold Cup (lost iron, bad trip)")
print("    * Fitness question after long break")
print()
print("#3 FULL SERRANO (12/1)")
print("  Record: 20: 7-6-2, $936,423")
print("  STRENGTHS:")
print("    * 2nd highest Prime Power (145.2)")
print("    * Won BC Dirt Mile-G1 in 2024")
print("    * Proven G1 performer")
print("    * Best Dirt Speed rating (120.0)")
print("  CONCERNS:")
print("    * 84 days since last race")
print("    * Last race: 5th in BC Dirt Mile (off form)")
print("    * Age 7 (oldest in field)")
print("    * Speed figure dropped to 86 last out")
print()
print("#1 DISCO TIME (8/5 Second Favorite)")
print("  Record: 5: 5-0-0, $551,960")
print("  STRENGTHS:")
print("    * UNDEFEATED in 5 career starts")
print("    * 3rd highest Prime Power (144.3)")
print("    * Won Dwyer Listed stakes last out")
print("    * High % trainer Brad Cox (32%)")
print("  CONCERNS:")
print("    * *** HUGE CLASS JUMP: Listed stakes to G1 ***")
print("    * Never faced G1 competition")
print("    * 77 days since last race")
print("    * Untested at this elite level")
print()
print("#7 TAPPAN STREET (6/1)")
print("  Record: 4: 3-1-0, $670,400")
print("  STRENGTHS:")
print("    * Won Florida Derby-G1")
print("    * Won last out (fresh form)")
print("    * Lightly raced (only 4 starts)")
print("    * 2nd off layoff (fitness edge)")
print("  CONCERNS:")
print("    * Last win was OC62500 (not stakes)")
print("    * Speed figure only 92 last out")
print("    * Florida Derby was weak field")
print("    * Unproven at this elite level")
print()
print("#4 BANISHING (20/1) - **OLD SYSTEM'S TOP PICK**")
print("  Record: 26: 9-6-3, $1,968,409")
print("  STRENGTHS:")
print("    * Highest career earnings $1.97M")
print("    * Won CT Classic-G2")
print("    * Multiple G2 victories")
print("  CONCERNS:")
print("    * *** OLD SYSTEM put him in A-Group alone ***")
print("    * 12th of 14 in BC Sprint (badly beaten)")
print("    * Speed figure only 97 last out")
print("    * Questionable G1 form")
print()

print("="*80)
print("CRITICAL DIFFERENCES: OLD vs NEW SYSTEM")
print("="*80)
print()
print("OLD SYSTEM PROBLEMS:")
print("  X Put #4 Banishing as solo A-Group pick (top win contender)")
print("  X Banishing went from ML 20/1 to Live 16/1 (not favored)")
print("  X Banishing was 12th in BC Sprint G1 (terrible form)")
print("  X #9 Captain Cook as 94.2% likely for 2nd")
print("  X Captain Cook speed figure only 89 (poor)")
print("  X Had #11 White Abarrio in C-Group (underneath)")
print("  X White Abarrio is defending champ with highest ratings!")
print()
print("NEW SYSTEM ADVANTAGES:")
print("  + Grade 1 = Level 10 class weight (MAXIMUM)")
print("  + Heavily rewards proven G1 performers")
print("  + #11 White Abarrio: Highest Prime Power + Class Rating")
print("  + #3 Full Serrano: Won BC Dirt Mile-G1, proven elite")
print("  + #1 Disco Time: Class jump from Listed to G1 flagged")
print("  + Speed figures and recent form weighed heavily")
print("  + Layoffs appropriately penalized")
print()

print("="*80)
print("NEW SYSTEM TOP 5 PREDICTIONS")
print("="*80)
print()
print("MOST LIKELY TOP 5 (New System Logic):")
print("  1. #11 White Abarrio (4/1) - Highest ratings, defending champ")
print("  2. #3 Full Serrano (12/1) - Proven G1 winner, strong power")
print("  3. #1 Disco Time (8/5) - Undefeated but facing class test")
print("  4. #7 Tappan Street (6/1) - Won Florida Derby, fresh")
print("  5. #6 Madaket Road (10/1) - Multiple G1 placings")
print()
print("SKEPTICAL OF:")
print("  * #4 Banishing (20/1) - Old system's top pick, poor G1 form")
print("  * #9 Captain Cook (15/1) - 98 day layoff, form dropped")
print("  * #2 British Isles (20/1) - Never won above OC80k")
print()

print("="*80)
print("RACE DYNAMICS & HANDICAPPING FACTORS")
print("="*80)
print()
print("GRADE 1 DIRT ROUTE PATTERNS:")
print("  * Early speed crucial (E/E-P types dominate)")
print("  * Recent form critical at this level")
print("  * Proven G1 winners have huge edge")
print("  * Class jumps from G3/Listed to G1 rarely succeed")
print("  * $3M purse = best horses show up")
print()
print("TRACK BIAS (Gulfstream Dirt Routes):")
print("  * Speed bias: 67% winners beaten lengths avg")
print("  * Wire-to-wire: 21% (pressure on pace)")
print("  * Posts 4-7: Slight advantage (1.15 impact)")
print("  * E/P running styles: 1.08 impact value")
print()

print("="*80)
print("VALIDATION POINTS")
print("="*80)
print()
print("We will check:")
print("  [ ] Did #4 Banishing win (old system A-Group)?")
print("  [ ] Did #9 Captain Cook finish 2nd (94.2% prediction)?")
print("  [ ] Did proven G1 winners (#11, #3) perform better?")
print("  [ ] Did #1 Disco Time handle the massive class jump?")
print("  [ ] Did Level 10 class weight reward elite performers?")
print()
print("This is THE ultimate test:")
print("  * Grade 1 Stakes (highest level)")
print("  * $3,000,000 purse (elite field)")
print("  * 14 horses (deep competition)")
print("  * Defending champion vs undefeated rising star")
print()
print("="*80)
print("READY FOR ACTUAL RESULTS!")
print("="*80)
print()
print("Please provide the finishing order and we will analyze")
print("how the new industry-standard hierarchy performed!")
print("="*80)
