# AUTO-CALIBRATED WEIGHTS
# Last Updated: 2026-02-05 19:32:29
# Generated by auto_calibration_engine.py

WEIGHTS = {
    'class': 3.01,  # Auto-tuned from 1 calibration events
    'speed': 2.42,  # Auto-tuned from 1 calibration events
    'form': 2.08,  # Auto-tuned from 1 calibration events
    'pace': 1.78,  # Auto-tuned from 1 calibration events
    'style': 2.28,  # Auto-tuned from 1 calibration events
    'post': 1.08,  # Auto-tuned from 1 calibration events
    'angles': 0.1,  # Auto-tuned from 1 calibration events
    'odds_drift_penalty': 3.0,  # Auto-tuned from 1 calibration events
    'smart_money_bonus': 2.5,  # Auto-tuned from 1 calibration events
    'a_group_drift_gate': 2.0,  # Auto-tuned from 1 calibration events
}
