# AUTO-CALIBRATED WEIGHTS
# Last Updated: 2026-02-13 10:35:43
# Generated by auto_calibration_engine.py

WEIGHTS = {
    'class': 4.0,  # Auto-tuned from 1 calibration events
    'speed': 4.0,  # Auto-tuned from 1 calibration events
    'form': 3.72,  # Auto-tuned from 1 calibration events
    'pace': 3.42,  # Auto-tuned from 1 calibration events
    'style': 3.92,  # Auto-tuned from 1 calibration events
    'post': 2.73,  # Auto-tuned from 1 calibration events
    'angles': 0.1,  # Auto-tuned from 1 calibration events
    'odds_drift_penalty': 3.0,  # Auto-tuned from 1 calibration events
    'smart_money_bonus': 2.5,  # Auto-tuned from 1 calibration events
    'a_group_drift_gate': 2.0,  # Auto-tuned from 1 calibration events
}
